// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/login" | "/records/new" | "/signup" | "/student/activate" | "/student/dashboard" | "/student/progress" | "/student/study/session" | "/student/wrong-answers" | "/students/manage" | "/study/content" | "/study/reviews" | "/wrong-answers/manage"
type AppRouteHandlerRoutes = "/api/v1/attempts" | "/api/v1/attempts/[attemptId]/items" | "/api/v1/auth/login" | "/api/v1/auth/logout" | "/api/v1/auth/signup" | "/api/v1/auth/student-activate" | "/api/v1/curriculum" | "/api/v1/dashboard/overview" | "/api/v1/dashboard/study-overview" | "/api/v1/dashboard/trends" | "/api/v1/dashboard/weakness" | "/api/v1/materials" | "/api/v1/student-workbooks" | "/api/v1/student-workbooks/[id]" | "/api/v1/student/dashboard/overview" | "/api/v1/student/dashboard/trends" | "/api/v1/student/study/board" | "/api/v1/student/study/concepts/[curriculumNodeId]" | "/api/v1/student/study/sessions" | "/api/v1/student/study/sessions/[id]/submit" | "/api/v1/student/workbook-progress" | "/api/v1/student/workbook-progress/dashboard" | "/api/v1/student/wrong-answers" | "/api/v1/student/wrong-answers/[id]" | "/api/v1/student/wrong-answers/[id]/image" | "/api/v1/student/wrong-notes" | "/api/v1/student/wrong-notes/[id]" | "/api/v1/student/wrong-notes/[id]/image" | "/api/v1/student/wrong-notes/chart" | "/api/v1/student/wrong-notes/dashboard" | "/api/v1/students" | "/api/v1/students/[id]/invite" | "/api/v1/students/[id]/invite/reset" | "/api/v1/study/content" | "/api/v1/study/content/concepts/[curriculumNodeId]" | "/api/v1/study/content/practice-sets" | "/api/v1/study/content/practice-sets/[id]" | "/api/v1/study/content/practice-sets/[id]/activation" | "/api/v1/study/progress" | "/api/v1/study/progress/[curriculumNodeId]" | "/api/v1/study/reviews" | "/api/v1/study/reviews/[sessionId]" | "/api/v1/workbook-progress" | "/api/v1/workbook-progress/dashboard" | "/api/v1/workbook-templates" | "/api/v1/workbook-templates/[id]" | "/api/v1/wrong-answers" | "/api/v1/wrong-answers/[id]/categories" | "/api/v1/wrong-answers/[id]/image" | "/api/v1/wrong-notes" | "/api/v1/wrong-notes/[id]" | "/api/v1/wrong-notes/[id]/feedback" | "/api/v1/wrong-notes/[id]/image" | "/api/v1/wrong-notes/chart" | "/api/v1/wrong-notes/dashboard"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/v1/attempts": {}
  "/api/v1/attempts/[attemptId]/items": { "attemptId": string; }
  "/api/v1/auth/login": {}
  "/api/v1/auth/logout": {}
  "/api/v1/auth/signup": {}
  "/api/v1/auth/student-activate": {}
  "/api/v1/curriculum": {}
  "/api/v1/dashboard/overview": {}
  "/api/v1/dashboard/study-overview": {}
  "/api/v1/dashboard/trends": {}
  "/api/v1/dashboard/weakness": {}
  "/api/v1/materials": {}
  "/api/v1/student-workbooks": {}
  "/api/v1/student-workbooks/[id]": { "id": string; }
  "/api/v1/student/dashboard/overview": {}
  "/api/v1/student/dashboard/trends": {}
  "/api/v1/student/study/board": {}
  "/api/v1/student/study/concepts/[curriculumNodeId]": { "curriculumNodeId": string; }
  "/api/v1/student/study/sessions": {}
  "/api/v1/student/study/sessions/[id]/submit": { "id": string; }
  "/api/v1/student/workbook-progress": {}
  "/api/v1/student/workbook-progress/dashboard": {}
  "/api/v1/student/wrong-answers": {}
  "/api/v1/student/wrong-answers/[id]": { "id": string; }
  "/api/v1/student/wrong-answers/[id]/image": { "id": string; }
  "/api/v1/student/wrong-notes": {}
  "/api/v1/student/wrong-notes/[id]": { "id": string; }
  "/api/v1/student/wrong-notes/[id]/image": { "id": string; }
  "/api/v1/student/wrong-notes/chart": {}
  "/api/v1/student/wrong-notes/dashboard": {}
  "/api/v1/students": {}
  "/api/v1/students/[id]/invite": { "id": string; }
  "/api/v1/students/[id]/invite/reset": { "id": string; }
  "/api/v1/study/content": {}
  "/api/v1/study/content/concepts/[curriculumNodeId]": { "curriculumNodeId": string; }
  "/api/v1/study/content/practice-sets": {}
  "/api/v1/study/content/practice-sets/[id]": { "id": string; }
  "/api/v1/study/content/practice-sets/[id]/activation": { "id": string; }
  "/api/v1/study/progress": {}
  "/api/v1/study/progress/[curriculumNodeId]": { "curriculumNodeId": string; }
  "/api/v1/study/reviews": {}
  "/api/v1/study/reviews/[sessionId]": { "sessionId": string; }
  "/api/v1/workbook-progress": {}
  "/api/v1/workbook-progress/dashboard": {}
  "/api/v1/workbook-templates": {}
  "/api/v1/workbook-templates/[id]": { "id": string; }
  "/api/v1/wrong-answers": {}
  "/api/v1/wrong-answers/[id]/categories": { "id": string; }
  "/api/v1/wrong-answers/[id]/image": { "id": string; }
  "/api/v1/wrong-notes": {}
  "/api/v1/wrong-notes/[id]": { "id": string; }
  "/api/v1/wrong-notes/[id]/feedback": { "id": string; }
  "/api/v1/wrong-notes/[id]/image": { "id": string; }
  "/api/v1/wrong-notes/chart": {}
  "/api/v1/wrong-notes/dashboard": {}
  "/dashboard": {}
  "/login": {}
  "/records/new": {}
  "/signup": {}
  "/student/activate": {}
  "/student/dashboard": {}
  "/student/progress": {}
  "/student/study/session": {}
  "/student/wrong-answers": {}
  "/students/manage": {}
  "/study/content": {}
  "/study/reviews": {}
  "/wrong-answers/manage": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
