// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(protected)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/records/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/records/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/records/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/student/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/student/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/student/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/progress">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/student/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/student/study/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/study/session">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/student/study/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/student/wrong-answers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/wrong-answers">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/student/wrong-answers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/students/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/students/manage">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/students/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/study/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/study/content">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/study/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/study/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/study/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/study/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(protected)/wrong-answers/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wrong-answers/manage">> = Specific
  const handler = {} as typeof import("../../../src/app/(protected)/wrong-answers/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(public)/student/activate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student/activate">> = Specific
  const handler = {} as typeof import("../../../src/app/(public)/student/activate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/attempts/[attemptId]/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/attempts/[attemptId]/items">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/attempts/[attemptId]/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/attempts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/attempts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/attempts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/student-activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/student-activate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/student-activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/curriculum/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/curriculum">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/curriculum/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/dashboard/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/dashboard/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/dashboard/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/dashboard/study-overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/dashboard/study-overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/dashboard/study-overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/dashboard/trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/dashboard/trends">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/dashboard/trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/dashboard/weakness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/dashboard/weakness">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/dashboard/weakness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/materials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/materials">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/materials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student-workbooks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student-workbooks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student-workbooks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student-workbooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student-workbooks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student-workbooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/dashboard/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/dashboard/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/dashboard/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/dashboard/trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/dashboard/trends">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/dashboard/trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/study/board/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/study/board">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/study/board/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/study/concepts/[curriculumNodeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/study/concepts/[curriculumNodeId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/study/concepts/[curriculumNodeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/study/sessions/[id]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/study/sessions/[id]/submit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/study/sessions/[id]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/study/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/study/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/study/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/workbook-progress/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/workbook-progress/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/workbook-progress/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/workbook-progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/workbook-progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/workbook-progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-answers/[id]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-answers/[id]/image">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-answers/[id]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-answers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-answers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-answers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-answers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-notes/[id]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-notes/[id]/image">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-notes/[id]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-notes/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-notes/chart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-notes/chart">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-notes/chart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-notes/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-notes/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-notes/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/student/wrong-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/student/wrong-notes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/student/wrong-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/students/[id]/invite/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/students/[id]/invite/reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/students/[id]/invite/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/students/[id]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/students/[id]/invite">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/students/[id]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/students">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/content/concepts/[curriculumNodeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/content/concepts/[curriculumNodeId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/content/concepts/[curriculumNodeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/content/practice-sets/[id]/activation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/content/practice-sets/[id]/activation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/content/practice-sets/[id]/activation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/content/practice-sets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/content/practice-sets/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/content/practice-sets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/content/practice-sets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/content/practice-sets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/content/practice-sets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/content">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/progress/[curriculumNodeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/progress/[curriculumNodeId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/progress/[curriculumNodeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/reviews/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/reviews/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/reviews/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/study/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/study/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/study/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/workbook-progress/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/workbook-progress/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/workbook-progress/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/workbook-progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/workbook-progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/workbook-progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/workbook-templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/workbook-templates/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/workbook-templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/workbook-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/workbook-templates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/workbook-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-answers/[id]/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-answers/[id]/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-answers/[id]/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-answers/[id]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-answers/[id]/image">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-answers/[id]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-answers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-notes/[id]/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-notes/[id]/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-notes/[id]/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-notes/[id]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-notes/[id]/image">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-notes/[id]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-notes/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-notes/chart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-notes/chart">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-notes/chart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-notes/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-notes/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-notes/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/wrong-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/wrong-notes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/wrong-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
